##Contact Endpoints

GET https://cse341-crudops.onrender.com/ HTTP/1.1
###
GET http://localhost:3000/ HTTP/1.1
###

##GET all
GET https://cse341-crudops.onrender.com/contact HTTP/1.1
###
GET http://localhost:3000/contact HTTP/1.1
###

##GET Single
GET https://cse341-crudops.onrender.com/contact/66285c77e05dadece0f8ef61 HTTP/1.1
###
GET http://localhost:3000/contact/66401c53e46a8b887d9ef82f HTTP/1.1
###

##GET filter
GET https://cse341-crudops.onrender.com/contact/gender/m HTTP/1.1
###
GET http://localhost:3000/contact/gender/m HTTP/1.1
###

###
POST http://localhost:3000/contact HTTP/1.1
content-type: application/json

{
    "contact": {
        "firstName": "Luke",
        "lastName": "Deer",
        "email": "deerluke@example.com",
        "phone": "123-456-7891",
        "relation": "Friend",
        "gender": "Male"
    },
    "address": {
        "street1": "123 Main St",
        "city": "Townville",
        "state": "Stateville",
        "country": "US",
        "zip": "12345"
  }
}

###
PUT http://localhost:3000/contact/66285c39e05dadece0f8ef60 HTTP/1.1
content-type: application/json
{
    "contact": {
        "address": "6640029983b39bf106a38b83"
    }
}

###
DELETE http://localhost:3000/contact/66401c53e46a8b887d9ef82f HTTP/1.1

###
DELETE https://cse341-crudops.onrender.com/contact/66401c53e46a8b887d9ef82f HTTP/1.1